export const numberListFrames = [
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-1",
    textTop: "Thời Trang Nam",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-1",
    textBottom: "Thời Trang Nữ",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-2",
    textTop: "Điện Thoại & Phụ Kiện",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-2",
    textBottom: "Mẹ & Bé",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-3",
    textTop: "Thiết Bị Điện Tử ",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-3",
    textBottom: "Nhà Cửa & Đời Sống",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-4",
    textTop: "Máy Tính & Láp Tốp",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-4",
    textBottom: "Sắc Đẹp",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-5",
    textTop: "Máy ảnh & Máy Quay Phim",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-5",
    textBottom: "Sức Khỏe",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-6",
    textTop: "Đòng Hồ",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-6",
    textBottom: "Giày Dép Nữ",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-7",
    textTop: "Giày Dép Nam",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-7",
    textBottom: "Túi Ví Nữ",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-8",
    textTop: "Thiết Bị Điện Gia Dụng",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-8",
    textBottom: "Phụ Kiện & Trang Sức Nữ",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-9",
    textTop: "Thể Thao & Du Lịch",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-9",
    textBottom: "Bách Hóa Online",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-10",
    textTop: "Ô Tô & Xe Máy & Xe Đạp",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-10",
    textBottom: "Nhà Sách Online",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-11",
    textTop: "Balo & Túi Ví Nam",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-11",
    textBottom: "Thời Trang Trẻ Em",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-12",
    textTop: "Đồ Chơi",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-12",
    textBottom: "Giặt Giũ & Chăm Sóc Nhà Cửa",
  },
  {
    classImageTop: "home__article--category-carousel_item__frames-image--top-13",
    textTop: "Chăm Sóc Thú Cưng",
    classImageBottom: "home__article--category-carousel_item__frames-image--bottom-13",
    textBottom: "Voucher & Dịch Vụ",
  },
];
